name: Setup deps
description: "Updates a dependency to its prerelease (tagged) version and synchronizes optional overrides."

inputs:
    package:
        required: true
        description: "Package name"
    tag:
        required: true
        description: "Tag"
    overrides:
        required: false
        description: "Space-separated list of packages that should override this dependency"

runs:
    using: 'composite'
    steps:
      - name: Setup dependency version
        shell: bash
        env:
            PACKAGE_NAME: ${{ inputs.package }}
            TAG: ${{ inputs.tag }}
            OVERRIDES: ${{ inputs.overrides }}
        run: |
            bash ${{ github.action_path }}/bin/run.sh
