name: "Setup GPG"
description: "Setup GPG"
inputs:
    id:
        required: true
        description: ""
    private-key:
        required: true
        description: ""
    passphrase:
        required: false
        description: ""
runs:
    using: "composite"
    steps:
      - name: Setup GPG
        env:
            GPG_ID: ${{ inputs.id }}
            GPG_PRIVATE_KEY: ${{ inputs.private-key }}
            GPG_PASSPHRASE: ${{ inputs.passphrase }}
        shell: bash
        run: |
            gpg --batch --import <<< "$GPG_PRIVATE_KEY"
            mkdir -p ~/.gnupg
            chmod 700 ~/.gnupg
            echo "batch" >> ~/.gnupg/gpg.conf
            echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
            echo "no-tty" >> ~/.gnupg/gpg.conf
            if [[ -n "$GPG_PASSPHRASE" ]]; then
                echo "allow-preset-passphrase" >> ~/.gnupg/gpg-agent.conf
                gpg-connect-agent reloadagent /bye
                KEYGRIP=$(gpg --with-keygrip --list-keys --fingerprint "$GPG_ID" | awk '/KEYGRIP/ { print $3 }')
                /usr/lib/gnupg/gpg-preset-passphrase --preset "$KEYGRIP" <<< "$GPG_PASSPHRASE"
            fi
            git config --global user.signingkey $GPG_ID
            git config commit.gpgsign true
            git config tag.gpgsign true
